#!/bin/bash

if [[ $(xrandr -q | grep " connected " | wc -l) == "1" ]]; then
  tag_names=({1..6})
  tag_keys=({1..6} 0)
  hc rename default "${tag_names[0]}" || true
  for i in "${!tag_names[@]}"; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ]; then
      hc keybind "$Mod-$key" use_index "$i"
      hc keybind "$Mod-Shift-$key" move_index "$i"
      hc keybind "$Mod-Control-$key" chain , move_index "$i" , use "$key"
    fi
  done
  ~/.config/herbstluftwm/polybar/launch_one.sh &
elif [[ $(xrandr -q | grep " connected " | wc -l) == "2" ]]; then
  tag_names=({1..5})
  tag_keys=({1..5} 0)
  source $HOME/.config/herbstluftwm/tag_per_monitor_2
  ~/.config/herbstluftwm/polybar/launch.sh &
elif [[ $(xrandr -q | grep " connected " | wc -l) == "3" ]]; then
  tag_names=({1..5})
  tag_keys=({1..5} 0)
  source $HOME/.config/herbstluftwm/tag_per_monitor_3
  ~/.config/herbstluftwm/polybar/launch.sh &
fi
