#!/usr/bin/env bash

SCRATCHPAD_NAME=$1

case "$1" in

Proton)
	entry="proton-mail"
	;;
Calc)
	entry="gnome-calculator"
	;;
esac

xdotool search --onlyvisible --class "$1" windowunmap || xdotool search --classname "$1" windowmap || $entry &
